trigger:
- none

pool:
  name: 'SelfHostedPool'

steps:
- task: Maven@3
  displayName: 'Execute Web Automation Test Suite'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: 'C:\Program Files\Java\jdk-17'
    goals: 'clean test'
    
    # CRUCIAL: Keeps the task running to parse and publish your test failures cleanly!
    testFailureIgnore: true
    
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'