# Maven
# Build your Java project and run tests with Apache Maven using your self-hosted agent.

trigger:
- master

pool:
  name: 'SelfHostedPool'

steps:
- task: Maven@3
  timeoutInMinutes: 30
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkUserInputPath: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'